---
- name: Configure app
  hosts: app
  become: true
  vars:
    db_host: 10.128.0.11
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: "0644"
      notify: Reload puma
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        mode: "0664"
        owner: ubuntu
        group: ubuntu
    - name: Enable puma
      systemd:
        name: puma
        enabled: true
  handlers:
    - name: Reload puma
      systemd:
        name: puma
        state: restarted
