---
- name: Configure Mongo database
  hosts: db
  become: true
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: "0644"
      notify: Restart database service
  vars:
    mongo_bind_ip: 0.0.0.0
  handlers:
    - name: Restart database service
      service:
        name: mongod
        state: restarted
