---
- name: Deploy app
  hosts: app
  tasks:
    - name: Get latest version of app
      ansible.builtin.git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
        version: monolith
      notify: Reload puma
    - name: Bundle install
      community.general.bundler:
        state: present
        chdir: /home/ubuntu/reddit
  handlers:
    - name: Reload puma
      become: true
      ansible.builtin.systemd:
        name: puma
        state: restarted
