---
- name: Configure hosts and apps
  hosts: all
  tasks:
    - name: Change mongo config file
      become: true
      ansible.builtin.template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: "0644"
      tags: db-tag
      notify: Restart database service
    - name: Add unit file for Puma
      become: true
      ansible.builtin.copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: "0644"
      tags: app-tag
      notify: Reload puma
    - name: Add config for DB connection
      ansible.builtin.template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        mode: "0664"
      tags: app-tag
    - name: Enable puma
      become: true
      ansible.builtin.systemd:
        name: puma
        enabled: true
      tags: app-tag
    - name: Get latest version of app
      ansible.builtin.git:
        repo: https://github.com/express42/reddit.git
        dest: /home/ubuntu/reddit
        version: monolith
      tags: deploy-tag
      notify: Reload puma
    - name: Bundle install
      community.general.bundler:
        state: present
        chdir: /home/ubuntu/reddit
      tags: deploy-tag
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.128.0.23
  handlers:
    - name: Restart database service
      become: true
      ansible.builtin.service:
        name: mongod
        state: restarted
    - name: Reload puma
      become: true
      ansible.builtin.systemd:
        name: puma
        state: restarted
